name: multicommander
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: File Manager For Professionals.
description: |
 multicommander contains a lot of features to make you efficent when working with files and folders.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-3-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-3-stable
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  multicommander:
    command: multicommander
    desktop: usr/share/applications/multicommander.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, hardware-observe, process-control, cups-control, removable-media, icon-themes, wine-runtime, wine-3-stable ]

parts:
  multicommander:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget http://multicommander.com/downloads -q -S -O - 2>&1 | grep 'version_' | head -n1 | sed 's|n_| |;s|">| |' | awk '{print $3}')
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_mc
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
    build-packages: [wget, unzip]
